routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ClientChatController;
use App\Http\Controllers\MerchantController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\RegisterController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\AdminUserController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\BrandController;
use App\Http\Controllers\Admin\AdminClientController;
use App\Http\Controllers\Admin\AdminProjectController;
use App\Http\Controllers\Admin\AdminTaskController;
use App\Http\Controllers\ProjectController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\TaskController;
use App\Http\Controllers\SubTaskController;
use App\Http\Controllers\InvoiceController;
use App\Http\Controllers\Admin\ServiceController;
use App\Http\Controllers\Admin\PackageController;
use App\Http\Controllers\Admin\CurrencyController;
use App\Http\Controllers\LogoFormController;
use App\Http\Controllers\VerifyController;
use App\Http\Controllers\WebFormController;
use App\Http\Controllers\SmmFormController;
use App\Http\Controllers\ContentWritingFormController;
use App\Http\Controllers\SeoFormController;
use App\Http\Controllers\SupportController;
use App\Http\Controllers\BookFormattingController;
use App\Http\Controllers\BookWritingController;
use App\Http\Controllers\AuthorWebsiteController;
use App\Http\Controllers\ProofreadingController;
use App\Http\Controllers\BookCoverController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
0 for seller, 1 for production, 2 for admin
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Client Links
Route::any('pay-now/{id}', [InvoiceController::class, 'payNow'])->name('client.paynow');
Route::post('/payment', [InvoiceController::class, 'paymentProcess'])->name('client.payment');
Route::any('thank-you/{id}', [InvoiceController::class, 'thankYou'])->name('thankYou');
Route::any('failed/{id}', [InvoiceController::class, 'failed'])->name('failed');

Route::group(['middleware' => 'auth'], function () {
    Route::post('/keep-alive', function () {
        if(auth()->user()->status == 0){
            return response()->json(['ok' => false]);
        }else{
            return response()->json(['ok' => true]);
        }
    });
});
Route::get('/', function () {
    return redirect()->route('login');
})->middleware('auth');

Auth::routes(['register' => false]);
Route::get('/send-notification/{task_id}/{role}', [TaskController::class, 'sendTaskNotification']);

Route::group(['middleware' => 'auth'], function () {
    Route::group(['middleware' => 'is_client'], function(){
        Route::get('client/home', [ClientController::class, 'clientTaskshow'])->name('client.home');
        Route::get('client/chat', [ClientChatController::class, 'clientChat'])->name('client.chat');
        Route::get('client/messages', [ClientController::class, 'clientTaskshow'])->name('client.fetch.messages');
        Route::post('client/messages', [ClientChatController::class, 'sendMessage'])->name('client.send.messages');
        Route::get('client/logo/{id}', [LogoFormController::class, 'index'])->name('client.logo.form');
        Route::get('client/web/{id}', [WebFormController::class, 'index'])->name('client.web.form');
        Route::get('client/smm/{id}', [SmmFormController::class, 'index'])->name('client.smm.form');
        Route::get('client/content/{id}', [ContentWritingFormController::class, 'index'])->name('client.content.form');
        Route::get('client/seo/{id}', [SeoFormController::class, 'index'])->name('client.seo.form');
        Route::post('client/logo/{id}', [LogoFormController::class, 'update'])->name('client.logo.form.update');
        Route::post('client/web/{id}', [WebFormController::class, 'update'])->name('client.web.form.update');
        Route::post('client/smm/{id}', [SmmFormController::class, 'update'])->name('client.smm.form.update');
        Route::post('client/content/{id}', [ContentWritingFormController::class, 'update'])->name('client.content.form.update');
        Route::post('client/seo/{id}', [SeoFormController::class, 'update'])->name('client.seo.form.update');
        Route::post('client/bookformatting/{id}', [BookFormattingController::class, 'update'])->name('client.bookformatting.form.update');
        Route::post('client/bookwriting/{id}', [BookWritingController::class, 'update'])->name('client.bookwriting.form.update');
        Route::post('client/authorwebsite/{id}', [AuthorWebsiteController::class, 'update'])->name('client.authorwebsite.form.update');
        Route::post('client/proofreading/{id}', [ProofreadingController::class, 'update'])->name('client.proofreading.form.update');
        Route::post('client/bookcover/{id}', [BookCoverController::class, 'update'])->name('client.bookcover.form.update');
        Route::post('client/logo', [LogoFormController::class, 'destroy'])->name('client.logo.form.file.delete');
        Route::get('client/projects', [ClientController::class, 'clientProject'])->name('client.project');
        Route::get('client/projects/view/{id}', [ClientController::class, 'clientProjectView'])->name('client.project.view');
        Route::get('client/task/show/{id}/{notify?}', [ClientController::class, 'clientTaskshow'])->name('client.task.show');
        Route::post('client/message/', [SupportController::class, 'sendMessageClient'])->name('client.message.send');
        Route::get('client/brief', [ClientController::class, 'getClientBrief'])->name('client.brief');
    });
});
Route::group(['middleware' => 'auth'], function () {
    Route::post('verify/code',  [AdminController::class, 'verifyCode'])->name('verify.code');
}); 
// Admin Routes
Route::group(['middleware' => 'auth'], function () {
    Route::group(['prefix' => 'admin',  'middleware' => 'is_admin'], function(){
        Route::get('home', [AdminController::class, 'dashboard'])->name('admin.home');
        Route::get('edit-profile', [AdminController::class, 'editProfile'])->name('admin.edit.profile');
        Route::patch('update-profile/{id}', [AdminController::class, 'updateProfile'])->name('admin.update.profile');
        Route::get('change-password', [AdminController::class, 'changePassword'])->name('admin.change.password');
        Route::post('change-password', [AdminController::class, 'updatePassword'])->name('admin.update.password');
        Route::get('user/production/create', [AdminUserController::class, 'getProductionUser'])->name('admin.user.production.create');
        Route::get('user/production', [AdminUserController::class, 'getUserProduction'])->name('admin.user.production');
        Route::post('user/status', [AdminUserController::class, 'updateStatus'])->name('update.user.status');
        Route::post('user/sale/password', [AdminUserController::class, 'updateSalePassword'])->name('update.user.update.password');
        Route::get('user/sales', [AdminUserController::class, 'getUserSale'])->name('admin.user.sales');
        Route::post('user/sales', [AdminUserController::class, 'storeUserSale'])->name('admin.user.sales.store');
        Route::post('user/production', [AdminUserController::class, 'storeUserSale'])->name('admin.user.production.store');
        Route::post('user/sales/password', [AdminUserController::class, 'passwordUserSale'])->name('admin.user.password');
        Route::get('user/create', [AdminUserController::class, 'createUserSale'])->name('admin.user.sales.create');
        Route::get('user/sale/edit/{id}', [AdminUserController::class, 'editUserSale'])->name('admin.user.sales.edit');
        Route::get('user/production/edit/{id}', [AdminUserController::class, 'editUserProduction'])->name('admin.user.production.edit');
        Route::post('user/sale/update/{id}', [AdminUserController::class, 'updateUserSale'])->name('admin.user.sales.update');
        Route::resource('category', CategoryController::class);
        Route::resource('brand', BrandController::class);
        Route::resource('service', ServiceController::class);
        Route::resource('package', PackageController::class);
        Route::resource('currency', CurrencyController::class);
        Route::get('/service-list/{id}', [HomeController::class, 'serviceList'])->name('admin.service.list');
        Route::resource('client', AdminClientController::class, ['names' => 'admin.client']);
        Route::resource('merchant', MerchantController::class, ['names' => 'admin.merchant']);
        Route::post('client/create_auth/', [AdminClientController::class, 'createAuth'])->name('admin.client.createauth');
        Route::post('client/update_auth/', [AdminClientController::class, 'updateAuth'])->name('admin.client.updateauth');
        Route::get('client/agent/{brand_id?}', [AdminClientController::class, 'getAgent'])->name('admin.client.agent');
        Route::post('assign/support/', [AdminClientController::class, 'assignSupport'])->name('admin.assign.support');
        Route::post('client/agent/update', [AdminClientController::class, 'updateAgent'])->name('admin.client.update.agent');
        Route::resource('project', AdminProjectController::class, ['names' => 'admin.project']);
        Route::resource('task', AdminTaskController::class, ['names' => 'admin.task']);
        Route::post('admin/subtask/store', [AdminTaskController::class, 'adminSubtaskStore'])->name('admin.subtask.store');
        Route::get('client/{client}/{id}', [AdminClientController::class, 'showNotification'])->name('admin.client.shownotification');
        Route::get('create-invoice/{id}', [InvoiceController::class, 'index'])->name('admin.invoice.index');

app/Models/Merchant.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Merchant extends Model
{
    use HasFactory;

    protected $table = 'merchants';
    protected $fillable = ['name', 'public_key', 'secret_key', 'status', 'login_id', 'is_authorized'];
}

app/Http/Controllers/MerchantController.php
<?php

namespace App\Http\Controllers;
use App\Models\Merchant;
use Illuminate\Http\Request;

class MerchantController extends Controller
{
    public function index(){
        $data = Merchant::all();
        return view('admin.merchant.index', compact('data'));
    }

    public function create(){
        return view('admin.merchant.create');
    }

    public function store(Request $request){
        $request->validate([
            'name' => 'required',
            'public_key' => 'required',
            'secret_key' => 'required',
            'status' => 'required',
        ]);
        $merchant = new Merchant();
        $merchant->name = $request->name;
        $merchant->public_key = $request->public_key;
        $merchant->secret_key = $request->secret_key;
        $merchant->status = $request->status;
        $merchant->login_id = $request->login_id;
        $merchant->is_authorized = $request->is_authorized;
        $merchant->save();
        return redirect()->route('admin.merchant.index')->with('success','Merchant created Successfully.');
    }

    public function edit($id){
        $data = Merchant::find($id);
        return view('admin.merchant.edit', compact('data'));
    }

    public function update(Request $request, Merchant $merchant){
        $request->validate([
            'name' => 'required',
            'public_key' => 'required',
            'secret_key' => 'required',
            'status' => 'required',
        ]);
        $merchant->update($request->except('_method', '_token'));
        return redirect()->route('admin.merchant.edit', $merchant->id)->with('success','Merchant Updated Successfully.');

    }
}

resources/views/admin/merchant/create.blade.php
@extends('layouts.app-admin')
@section('title', 'Create Merchant')
@section('content')

<div class="breadcrumb">
    <h1>Create Merchant</h1>
    <ul>
        <li><a href="#">Merchant</a></li>
        <li>Create Merchant</li>
    </ul>
</div>
<div class="separator-breadcrumb border-top"></div>
<div class="row">
    <div class="col-md-12">
        <div class="card mb-4">
            <div class="card-body">
                <div class="card-title mb-3">Merchant Form</div>
                <form class="form" action="{{route('admin.merchant.store')}}" method="POST" enctype="multipart/form-data">
                    @csrf   
                    <div class="form-body">
                        <div class="row">
                            <div class="col-md-12 form-group mb-3">
                                <label for="name">Name <span>*</span></label>
                                <input type="text" id="name" class="form-control" value="{{old('name')}}" placeholder="Name" name="name" required="required">
                                @error('name')
                                <div class="invalid-feedback">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="col-md-12 form-group mb-3">                                
                                <label for="public_key">Public Key <span>*</span></label>
                                <input type="text" id="public_key" class="form-control" value="{{old('public_key')}}" placeholder="Public Key" name="public_key" required="required">
                                @error('public_key')
                                <div class="invalid-feedback">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="col-md-12 form-group mb-3">
                                <label for="secret_key">Secret Key <span>*</span></label>
                                <input type="text" id="secret_key" class="form-control" value="{{old('secret_key')}}" placeholder="Secret Key" name="secret_key" required="required">
                                @error('secret_key')
                                <div class="invalid-feedback">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="col-md-12 form-group mb-3">
                                <label for="secret_key">Login ID<span>(If Authorize.net Payment)</span></label>
                                <input type="text" id="login_id" class="form-control" value="{{old('login_id')}}" placeholder="Secret Key" name="login_id">
                            </div>
                            <div class="col-md-12 form-group mb-3">
                                <label for="is_authorized">Select Merchant Type <span>*</span></label>
                                <select name="is_authorized" id="is_authorized" class="form-control" >
                                    <option value="">Select Merchant Type</option>
                                    <option value="1">Stripe</option>
                                    <option value="2">Authorize.net</option>
                                </select>
                            </div>
                            <div class="col-md-12 form-group mb-3">
                                <label for="status">Select Status <span>*</span></label>
                                <select name="status" id="status" class="form-control" >
                                    <option value="1">Active</option>
                                    <option value="0">Deactive</option>
                                </select>
                            </div>
                            <div class="col-md-12">
                                <button class="btn btn-primary" type="submit">Save Merchant</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@endsection

@push('scripts')
   
@endpush

resources/views/admin/merchant/edit.blade.php
@extends('layouts.app-admin')
@section('content')
<div class="breadcrumb row">
    <div class="col-md-6">
        <h1 class="mr-2">Edit Merchant (ID: {{$data->id}})</h1>
        <ul>
            <li><a href="{{route('admin.merchant.index')}}">Merchant</a></li>
            <li>Edit Merchant</li>
        </ul>
    </div>
    <div class="col-md-6 text-right">
        <a href="{{ route('admin.merchant.index') }}" class="btn btn-primary">Back to Merchants</a>
    </div>
</div>
<div class="separator-breadcrumb border-top"></div>

<div class="row">
    <div class="col-md-12">
        <div class="card mb-4">
            <div class="card-body">
                <div class="card-title mb-3">Merchant Form</div>
                <form class="form" action="{{route('admin.merchant.update',$data->id)}}" method="POST" enctype="multipart/form-data">
                    @csrf
                    @method('PATCH')  
                    <div class="form-body">
                        <div class="row">
                            <div class="col-md-12 form-group mb-3">
                                <label for="name">Name <span>*</span></label>
                                <input type="text" id="name" class="form-control" value="{{old('name', $data->name)}}" placeholder="Name" name="name" required="required">
                                @error('name')
                                <div class="invalid-feedback">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="col-md-12 form-group mb-3">                                
                                <label for="public_key">Public Key <span>*</span></label>
                                <input type="text" id="public_key" class="form-control" value="{{old('public_key', $data->public_key)}}" placeholder="Public Key" name="public_key" required="required">
                                @error('public_key')
                                <div class="invalid-feedback">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="col-md-12 form-group mb-3">
                                <label for="secret_key">Secret Key <span>*</span></label>
                                <input type="text" id="secret_key" class="form-control" value="{{old('secret_key', $data->secret_key)}}" placeholder="Secret Key" name="secret_key" required="required">
                                @error('secret_key')
                                <div class="invalid-feedback">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="col-md-12 form-group mb-3">
                                <label for="secret_key">Login ID<span>(If Authorize.net Payment)</span></label>
                                <input type="text" id="login_id" class="form-control" value="{{old('login_id', $data->login_id)}}" placeholder="Secret Key" name="login_id">
                            </div>
                            <div class="col-md-12 form-group mb-3">
                                <label for="status">Select Status <span>*</span></label>
                                <select name="status" id="status" class="form-control" >
                                    <option value="1" {{ $data->status == 1 ? 'selected' : ' ' }}>Active</option>
                                    <option value="0" {{ $data->status == 0 ? 'selected' : ' ' }}>Deactive</option>
                                </select>
                            </div>
                            <div class="col-md-12">
                                <button class="btn btn-primary" type="submit">Update Merchant</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@stop
@section('script')
@endsection

resources/views/admin/merchant/index.blade.php
@extends('layouts.app-admin')
@section('title', 'Merchants')
@push('styles')
<style>
    .select2-container {
        z-index: 9999;
        text-align: left;
    }
</style>
@endpush
@section('content')
<div class="breadcrumb row">
    <div class="col-md-6">
        <h1 class="mr-2">Merchants</h1>
    </div>
    <div class="col-md-6 text-right">
        <a href="{{ route('admin.merchant.create') }}" class="btn btn-primary">Create Merchant</a>
    </div>
</div>
<div class="separator-breadcrumb border-top"></div>

<div class="row">
    <div class="col-md-12">
        <div class="card text-left">
            <div class="card-body">
                <h4 class="card-title mb-3 count-card-title">Merchant's Details <span> Total: {{ count($data) }} <span></h4>
                <div class="table-responsive">
                    <table class="display table table-striped table-bordered"  style="width:100%">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Name</th>
                                <th>Public Key</th>
                                <th>Secret Key</th>
                                <th>Merchant</th>
                                <th>Status</th>
                                <th>Active</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($data as $datas)
                            <tr>
                                <td>{{$datas->id}}</td>
                                <td>{{$datas->name}}</td>
                                <td style="overflow-wrap: anywhere;">{{$datas->public_key}}</td>
                                <td style="overflow-wrap: anywhere;">{{$datas->secret_key}}</td>
                                <td>
                                    @if($datas->is_authorized == 0)
                                    <button class="btn btn-sm btn-secondary">STRIPE</button>
                                    @else
                                    <button class="btn btn-sm btn-secondary">AUTHORIZE.NET</button>
                                    @endif
                                </td>
                                <td>
                                    @if($datas->status == 1)
                                        <button class="btn btn-success btn-sm">Active</button><br>
                                    @else
                                        <button class="btn btn-danger btn-sm">Deactive</button><br>
                                    @endif
                                </td>
                                <td>
                                    <a href="{{ route('admin.merchant.edit', $datas->id) }}" class="btn btn-primary btn-icon btn-sm">
                                        <span class="ul-btn__icon"><i class="i-Edit"></i></span>
                                        <span class="ul-btn__text">Edit</span>
                                    </a>
                                </td>
                            </tr>
                            @endforeach
                            
                        </tbody>
                        <tfoot>
                            <tr>
                                <th>ID</th>
                                <th>Name</th>
                                <th>Public Key</th>
                                <th>Secret Key</th>
                                <th>Merchant</th>
                                <th>Status</th>
                                <th>Active</th>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<meta name="csrf-token" content="{{ csrf_token() }}">
@endsection

@push('scripts')

@endpush