routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ClientChatController;
use App\Http\Controllers\MerchantController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\RegisterController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\AdminUserController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\BrandController;
use App\Http\Controllers\Admin\AdminClientController;
use App\Http\Controllers\Admin\AdminProjectController;
use App\Http\Controllers\Admin\AdminTaskController;
use App\Http\Controllers\ProjectController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\TaskController;
use App\Http\Controllers\SubTaskController;
use App\Http\Controllers\InvoiceController;
use App\Http\Controllers\Admin\ServiceController;
use App\Http\Controllers\Admin\PackageController;
use App\Http\Controllers\Admin\CurrencyController;
use App\Http\Controllers\LogoFormController;
use App\Http\Controllers\VerifyController;
use App\Http\Controllers\WebFormController;
use App\Http\Controllers\SmmFormController;
use App\Http\Controllers\ContentWritingFormController;
use App\Http\Controllers\SeoFormController;
use App\Http\Controllers\SupportController;
use App\Http\Controllers\BookFormattingController;
use App\Http\Controllers\BookWritingController;
use App\Http\Controllers\AuthorWebsiteController;
use App\Http\Controllers\ProofreadingController;
use App\Http\Controllers\BookCoverController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
0 for seller, 1 for production, 2 for admin
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Client Links
Route::any('pay-now/{id}', [InvoiceController::class, 'payNow'])->name('client.paynow');
Route::post('/payment', [InvoiceController::class, 'paymentProcess'])->name('client.payment');
Route::any('thank-you/{id}', [InvoiceController::class, 'thankYou'])->name('thankYou');
Route::any('failed/{id}', [InvoiceController::class, 'failed'])->name('failed');

Route::group(['middleware' => 'auth'], function () {
    Route::post('/keep-alive', function () {
        if(auth()->user()->status == 0){
            return response()->json(['ok' => false]);
        }else{
            return response()->json(['ok' => true]);
        }
    });
});
Route::get('/', function () {
    return redirect()->route('login');
})->middleware('auth');

Auth::routes(['register' => false]);
Route::get('/send-notification/{task_id}/{role}', [TaskController::class, 'sendTaskNotification']);

Route::group(['middleware' => 'auth'], function () {
    Route::group(['middleware' => 'is_client'], function(){
        Route::get('client/home', [ClientController::class, 'clientTaskshow'])->name('client.home');
        Route::get('client/chat', [ClientChatController::class, 'clientChat'])->name('client.chat');
        Route::get('client/messages', [ClientController::class, 'clientTaskshow'])->name('client.fetch.messages');
        Route::post('client/messages', [ClientChatController::class, 'sendMessage'])->name('client.send.messages');
        Route::get('client/logo/{id}', [LogoFormController::class, 'index'])->name('client.logo.form');
        Route::get('client/web/{id}', [WebFormController::class, 'index'])->name('client.web.form');
        Route::get('client/smm/{id}', [SmmFormController::class, 'index'])->name('client.smm.form');
        Route::get('client/content/{id}', [ContentWritingFormController::class, 'index'])->name('client.content.form');
        Route::get('client/seo/{id}', [SeoFormController::class, 'index'])->name('client.seo.form');
        Route::post('client/logo/{id}', [LogoFormController::class, 'update'])->name('client.logo.form.update');
        Route::post('client/web/{id}', [WebFormController::class, 'update'])->name('client.web.form.update');
        Route::post('client/smm/{id}', [SmmFormController::class, 'update'])->name('client.smm.form.update');
        Route::post('client/content/{id}', [ContentWritingFormController::class, 'update'])->name('client.content.form.update');
        Route::post('client/seo/{id}', [SeoFormController::class, 'update'])->name('client.seo.form.update');
        Route::post('client/bookformatting/{id}', [BookFormattingController::class, 'update'])->name('client.bookformatting.form.update');
        Route::post('client/bookwriting/{id}', [BookWritingController::class, 'update'])->name('client.bookwriting.form.update');
        Route::post('client/authorwebsite/{id}', [AuthorWebsiteController::class, 'update'])->name('client.authorwebsite.form.update');
        Route::post('client/proofreading/{id}', [ProofreadingController::class, 'update'])->name('client.proofreading.form.update');
        Route::post('client/bookcover/{id}', [BookCoverController::class, 'update'])->name('client.bookcover.form.update');
        Route::post('client/logo', [LogoFormController::class, 'destroy'])->name('client.logo.form.file.delete');
        Route::get('client/projects', [ClientController::class, 'clientProject'])->name('client.project');
        Route::get('client/projects/view/{id}', [ClientController::class, 'clientProjectView'])->name('client.project.view');
        Route::get('client/task/show/{id}/{notify?}', [ClientController::class, 'clientTaskshow'])->name('client.task.show');
        Route::post('client/message/', [SupportController::class, 'sendMessageClient'])->name('client.message.send');
        Route::get('client/brief', [ClientController::class, 'getClientBrief'])->name('client.brief');
    });
});
Route::group(['middleware' => 'auth'], function () {
    Route::post('verify/code',  [AdminController::class, 'verifyCode'])->name('verify.code');
}); 
// Admin Routes
Route::group(['middleware' => 'auth'], function () {
    Route::group(['prefix' => 'admin',  'middleware' => 'is_admin'], function(){
        Route::get('home', [AdminController::class, 'dashboard'])->name('admin.home');
        Route::get('edit-profile', [AdminController::class, 'editProfile'])->name('admin.edit.profile');
        Route::patch('update-profile/{id}', [AdminController::class, 'updateProfile'])->name('admin.update.profile');
        Route::get('change-password', [AdminController::class, 'changePassword'])->name('admin.change.password');
        Route::post('change-password', [AdminController::class, 'updatePassword'])->name('admin.update.password');
        Route::get('user/production/create', [AdminUserController::class, 'getProductionUser'])->name('admin.user.production.create');
        Route::get('user/production', [AdminUserController::class, 'getUserProduction'])->name('admin.user.production');
        Route::post('user/status', [AdminUserController::class, 'updateStatus'])->name('update.user.status');
        Route::post('user/sale/password', [AdminUserController::class, 'updateSalePassword'])->name('update.user.update.password');
        Route::get('user/sales', [AdminUserController::class, 'getUserSale'])->name('admin.user.sales');
        Route::post('user/sales', [AdminUserController::class, 'storeUserSale'])->name('admin.user.sales.store');
        Route::post('user/production', [AdminUserController::class, 'storeUserSale'])->name('admin.user.production.store');
        Route::post('user/sales/password', [AdminUserController::class, 'passwordUserSale'])->name('admin.user.password');
        Route::get('user/create', [AdminUserController::class, 'createUserSale'])->name('admin.user.sales.create');
        Route::get('user/sale/edit/{id}', [AdminUserController::class, 'editUserSale'])->name('admin.user.sales.edit');
        Route::get('user/production/edit/{id}', [AdminUserController::class, 'editUserProduction'])->name('admin.user.production.edit');
        Route::post('user/sale/update/{id}', [AdminUserController::class, 'updateUserSale'])->name('admin.user.sales.update');
        Route::resource('category', CategoryController::class);
        Route::resource('brand', BrandController::class);
        Route::resource('service', ServiceController::class);
        Route::resource('package', PackageController::class);
        Route::resource('currency', CurrencyController::class);
        Route::get('/service-list/{id}', [HomeController::class, 'serviceList'])->name('admin.service.list');
        Route::resource('client', AdminClientController::class, ['names' => 'admin.client']);
        Route::resource('merchant', MerchantController::class, ['names' => 'admin.merchant']);
        Route::post('client/create_auth/', [AdminClientController::class, 'createAuth'])->name('admin.client.createauth');
        Route::post('client/update_auth/', [AdminClientController::class, 'updateAuth'])->name('admin.client.updateauth');
        Route::get('client/agent/{brand_id?}', [AdminClientController::class, 'getAgent'])->name('admin.client.agent');
        Route::post('assign/support/', [AdminClientController::class, 'assignSupport'])->name('admin.assign.support');
        Route::post('client/agent/update', [AdminClientController::class, 'updateAgent'])->name('admin.client.update.agent');
        Route::resource('project', AdminProjectController::class, ['names' => 'admin.project']);
        Route::resource('task', AdminTaskController::class, ['names' => 'admin.task']);
        Route::post('admin/subtask/store', [AdminTaskController::class, 'adminSubtaskStore'])->name('admin.subtask.store');
        Route::get('client/{client}/{id}', [AdminClientController::class, 'showNotification'])->name('admin.client.shownotification');
        Route::get('create-invoice/{id}', [InvoiceController::class, 'index'])->name('admin.invoice.index');

app/Models/Task.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Auth;
use DateTime;

class Task extends Model
{
    use HasFactory;
    protected $table = 'tasks';
    protected $fillable = ['project_id', 'category_id', 'description', 'status', 'user_id', 'brand_id', 'created_at', 'duedate', 'notes'];

    public function projects(){
        return $this->belongsTo(Project::class, 'project_id');
    }

    public function user(){
        return $this->hasOne(User::class, 'id', 'user_id');
    }

    public function brand(){
        return $this->hasOne(Brand::class, 'id', 'brand_id');
    }

    public function category(){
        return $this->hasOne(Category::class, 'id', 'category_id');
    }

    public function subtaskDueDate(){
        return $this->hasOne(SubTask::class, 'task_id', 'id')->whereNotNull('duedate')->orderBy('id', 'desc');
    }

    public function project_status(){
        // 0 for open
        // 1 for re_open
        // 2 for hold
        // 3 for completed
        // 4 for in_progress
        $status = $this->status;
        if($status == 0){
            return "<button class='btn btn-danger btn-sm'>Open</button>";
        }else if($status == 1){
            return "<button class='btn btn-primary btn-sm'>Re Open</button>";
        }else if($status == 2){
            return "<button class='btn btn-info btn-sm'>Hold</button>";
        }else if($status == 3){
            return "<button class='btn btn-success btn-sm'>Completed</button>";
        }else if($status == 4){
            return "<button class='btn btn-warning btn-sm'>In Progress</button>";
        }else if($status == 5){
            return "<button class='btn btn-info btn-sm'>Sent for Approval</button>";
        }else if($status == 6){
            return "<button class='btn btn-warning btn-sm'>Incomplete Brief</button>";
        }
    }

    public function client_files(){
        return $this->hasMany(ClientFile::class, 'task_id', 'id')->orderBy('id', 'desc')->where('message_id', 0);
    }

    public function client_files_support(){
        return $this->hasMany(ClientFile::class, 'task_id', 'id')->whereIn('production_check', [1,2])->where('message_id', 0)->orderBy('id', 'desc');
    }

    public function client_files_to_shown(){
        return $this->hasMany(ClientFile::class, 'task_id', 'id')->where('show_to_client', Auth::user()->id)->orderBy('id', 'desc');
    }

    public function count_files(){
        return $this->hasMany(ClientFile::class, 'task_id', 'id')->count();
    }

    public function sub_tasks(){
        return $this->hasMany(SubTask::class, 'task_id', 'id')->where('sub_task_id', 0)->orderBy('id', 'desc');
    }

    public function messages(){
        return $this->hasMany(Message::class, 'task_id', 'id')->orderBy('id', 'desc');
    }

    public function getDueDate(){
        $date_string = '';
        $date_now = new DateTime();
        if(count($this->sub_tasks) == 0){
            $date2 = new DateTime(date('d-m-Y', strtotime($this->duedate)));
            $date_string = $this->duedate;
        }else{
            $date_string = "";
            $date2 = "";
            if($this->getSubtaskDueDate != null){
                $date2 = new DateTime(date('d-m-Y', strtotime($this->getSubtaskDueDate->duedate)));
                $date_string = $this->getSubtaskDueDate->duedate;
            }else{
                $date2 = new DateTime(date('d-m-Y', strtotime($this->duedate)));
                $date_string = $this->duedate;
            }
            
            // if($this->subtaskDueDate != null){
            //     if($this->subtaskDueDate->duedateChange != null){
            //         $date2 = new DateTime(date('d-m-Y', strtotime($this->subtaskDueDate->duedateChange->duadate)));
            //         $date_string = $this->subtaskDueDate->duedateChange->duadate;
            //     }else{
            //         $date2 = new DateTime(date('d-m-Y', strtotime($this->subtaskDueDate->duedate)));
            //         $date_string = $this->subtaskDueDate->duedate;
            //     }
            // }else{
            //     $date2 = new DateTime(date('d-m-Y', strtotime($this->duedate)));
            //     $date_string = $this->duedate;
            // }
        }
        
        $button = '';
        if ($date_now > $date2){
            $button.= '<button class="btn btn-danger btn-sm">';
        }else{
            $button.= '<button class="btn btn-success btn-sm">';
        }

        $button .= date('d-m-Y', strtotime($date_string)) . '</button>';
        return $button;
    }
    public function todaySubtask(){
  
        return $this->hasMany(SubTask::class, 'task_id', 'id')->whereNotNull('duedate')->where('sub_task_id', 0)->where('duedate', date('Y-m-d'));
    }

    public function getSubtaskDueDate(){
        return $this->hasOne(SubTask::class, 'task_id', 'id')->whereNotNull('duedate')->where('sub_task_id', 0)->orderBy('duedate', 'desc');
    }

    public function member_list(){
        return $this->hasMany(TaskMemberList::class, 'task_id', 'id');
    }
}

resources/views/admin/task/index.blade.php
@extends('layouts.app-admin')
   
@section('content')
<div class="breadcrumb">
    <h1 class="mr-2">Tasks</h1>
</div>
<div class="separator-breadcrumb border-top"></div>

<div class="row mb-4">
    <div class="col-md-12">
        <div class="card text-left">
            <div class="card-body">
                <form class="form">
                    <div class="form-body">
                        <div class="row">
                            <div class="col-md-3 form-group mb-3">
                                <label for="brand">Search From Brand</label>
                                <select name="brand" class="form-control select2" >
                                    <option value="">All Brand</option>
                                    @foreach($brands as $brand)
                                    <option value="{{$brand->id}}" {{ Request::get('brand') ==  $brand->id ? 'selected' : ' '}}>{{$brand->name}}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="col-md-3 form-group mb-0">
                                <label for="brand">Search From Client Name Or Email</label>
                                <input type="text" class="form-control" id="name" name="name" value="{{ Request::get('name') }}">
                            </div>
                            <div class="col-md-3 form-group mb-0">
                                <label for="agent">Search From Agent Name</label>
                                <input type="text" class="form-control" id="agent" name="agent" value="{{ Request::get('agent') }}">
                            </div>
                            <div class="col-md-3 form-group mb-0">
                                <label for="category">Search From Category</label>
                                <select name="category" class="form-control select2" >
                                    <option value="">Any</option>
                                    @foreach($categorys as $category)
                                    <option value="{{$category->id}}" {{ Request::get('category') ==  $category->id ? 'selected' : ' '}}>{{$category->name}}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="col-md-3 form-group mb-0">
                                <label for="status">Status</label>
                                <select name="status" id="status" class="form-control">
                                    <option value="" {{ Request::get('status') ==  null ? 'selected' : ''}}>Any</option>
                                    <option value="0" {{ Request::get('status') ==  '0' ? 'selected' : ''}}>Open</option>
                                    <option value="1" {{ Request::get('status') ==  '1' ? 'selected' : ''}}>Re Open</option>
                                    <option value="5" {{ Request::get('status') ==  '5' ? 'selected' : ''}}>Sent for Approval</option>
                                    <option value="6" {{ Request::get('status') ==  '6' ? 'selected' : ''}}>Incomplete Brief</option>
                                    <option value="2" {{ Request::get('status') ==  '2' ? 'selected' : ''}}>Hold</option>
                                    <option value="3" {{ Request::get('status') ==  '3' ? 'selected' : ''}}>Completed</option>
                                </select>
                            </div>
                            <div class="col-md-12">
                                <div class="text-right">
                                    <button class="btn btn-primary" type="submit">Search Result</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="card text-left">
            <div class="card-body">
                <h4 class="card-title mb-3 count-card-title">Task Details <span> Total: {{ $data->total() }} <span></h4>
                <div class="table-responsive">
                    <table class="display table table-striped table-bordered" style="width:100%">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Task</th>
                                <th>Project Name</th>
                                <th>Client</th>
                                <th>Agent</th>
                                <th>Brand/Category</th>
                                <th>Status</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($data as $datas)
                            <tr>
                                <td>{{$datas->id}}</td>
                                <td><a href="{{route('admin.task.show', $datas->id)}}">{!! \Illuminate\Support\Str::limit(strip_tags($datas->description), 25, $end='...') !!}</a></td>
                                <td>{{$datas->projects->name}}</td>
                                <td>{{$datas->projects->client->name}} {{$datas->projects->client->last_name}}</td>
                                <td>{{$datas->user->name}} {{$datas->user->last_name}}</td>
                                <td>
                                    <a class="btn btn-primary btn-sm" title="{{$datas->brand->name}}" href="javascript:;">{{ implode('', array_map(function($v) { return $v[0]; }, explode(' ', $datas->brand->name))) }}</a>
                                    <a class="btn btn-info btn-sm" title="{{$datas->category->name}}" href="javascript:;">{{ implode('', array_map(function($v) { return $v[0]; }, explode(' ', $datas->category->name))) }}</a>
                                </td>
                                <td>{!! $datas->project_status() !!}</td>
                                <td>
                                <!-- {{ route('admin.task.edit', $datas->id) }}  -->
                                    <a href="{{route('admin.task.show', $datas->id)}}" target="_blank" class="btn btn-primary btn-icon btn-sm">
                                        <span class="ul-btn__icon"><i class="i-Eye"></i></span>
                                    </a>
                                </td>
                            </tr>
                            @endforeach
                            
                        </tbody>
                        <tfoot>
                            <tr>
                                <th>ID</th>
                                <th>Task</th>
                                <th>Project Name</th>
                                <th>Client</th>
                                <th>Agent</th>
                                <th>Brand/Category</th>
                                <th>Status</th>
                                <th></th>
                            </tr>
                        </tfoot>
                    </table>
                    {{ $data->appends(['brand' => Request::get('brand'), 'name' => Request::get('name'), 'agent' => Request::get('agent'), 'category' => Request::get('category'), 'status' => Request::get('status')])->links("pagination::bootstrap-4") }}
                </div>
            </div>
        </div>
    </div>
</div>


@endsection

@push('scripts')
    
@endpush