routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ClientChatController;
use App\Http\Controllers\MerchantController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\RegisterController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\AdminUserController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\BrandController;
use App\Http\Controllers\Admin\AdminClientController;
use App\Http\Controllers\Admin\AdminProjectController;
use App\Http\Controllers\Admin\AdminTaskController;
use App\Http\Controllers\ProjectController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\TaskController;
use App\Http\Controllers\SubTaskController;
use App\Http\Controllers\InvoiceController;
use App\Http\Controllers\Admin\ServiceController;
use App\Http\Controllers\Admin\PackageController;
use App\Http\Controllers\Admin\CurrencyController;
use App\Http\Controllers\LogoFormController;
use App\Http\Controllers\VerifyController;
use App\Http\Controllers\WebFormController;
use App\Http\Controllers\SmmFormController;
use App\Http\Controllers\ContentWritingFormController;
use App\Http\Controllers\SeoFormController;
use App\Http\Controllers\SupportController;
use App\Http\Controllers\BookFormattingController;
use App\Http\Controllers\BookWritingController;
use App\Http\Controllers\AuthorWebsiteController;
use App\Http\Controllers\ProofreadingController;
use App\Http\Controllers\BookCoverController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
0 for seller, 1 for production, 2 for admin
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Client Links
Route::any('pay-now/{id}', [InvoiceController::class, 'payNow'])->name('client.paynow');
Route::post('/payment', [InvoiceController::class, 'paymentProcess'])->name('client.payment');
Route::any('thank-you/{id}', [InvoiceController::class, 'thankYou'])->name('thankYou');
Route::any('failed/{id}', [InvoiceController::class, 'failed'])->name('failed');

Route::group(['middleware' => 'auth'], function () {
    Route::post('/keep-alive', function () {
        if(auth()->user()->status == 0){
            return response()->json(['ok' => false]);
        }else{
            return response()->json(['ok' => true]);
        }
    });
});
Route::get('/', function () {
    return redirect()->route('login');
})->middleware('auth');

Auth::routes(['register' => false]);
Route::get('/send-notification/{task_id}/{role}', [TaskController::class, 'sendTaskNotification']);

Route::group(['middleware' => 'auth'], function () {
    Route::group(['middleware' => 'is_client'], function(){
        Route::get('client/home', [ClientController::class, 'clientTaskshow'])->name('client.home');
        Route::get('client/chat', [ClientChatController::class, 'clientChat'])->name('client.chat');
        Route::get('client/messages', [ClientController::class, 'clientTaskshow'])->name('client.fetch.messages');
        Route::post('client/messages', [ClientChatController::class, 'sendMessage'])->name('client.send.messages');
        Route::get('client/logo/{id}', [LogoFormController::class, 'index'])->name('client.logo.form');
        Route::get('client/web/{id}', [WebFormController::class, 'index'])->name('client.web.form');
        Route::get('client/smm/{id}', [SmmFormController::class, 'index'])->name('client.smm.form');
        Route::get('client/content/{id}', [ContentWritingFormController::class, 'index'])->name('client.content.form');
        Route::get('client/seo/{id}', [SeoFormController::class, 'index'])->name('client.seo.form');
        Route::post('client/logo/{id}', [LogoFormController::class, 'update'])->name('client.logo.form.update');
        Route::post('client/web/{id}', [WebFormController::class, 'update'])->name('client.web.form.update');
        Route::post('client/smm/{id}', [SmmFormController::class, 'update'])->name('client.smm.form.update');
        Route::post('client/content/{id}', [ContentWritingFormController::class, 'update'])->name('client.content.form.update');
        Route::post('client/seo/{id}', [SeoFormController::class, 'update'])->name('client.seo.form.update');
        Route::post('client/bookformatting/{id}', [BookFormattingController::class, 'update'])->name('client.bookformatting.form.update');
        Route::post('client/bookwriting/{id}', [BookWritingController::class, 'update'])->name('client.bookwriting.form.update');
        Route::post('client/authorwebsite/{id}', [AuthorWebsiteController::class, 'update'])->name('client.authorwebsite.form.update');
        Route::post('client/proofreading/{id}', [ProofreadingController::class, 'update'])->name('client.proofreading.form.update');
        Route::post('client/bookcover/{id}', [BookCoverController::class, 'update'])->name('client.bookcover.form.update');
        Route::post('client/logo', [LogoFormController::class, 'destroy'])->name('client.logo.form.file.delete');
        Route::get('client/projects', [ClientController::class, 'clientProject'])->name('client.project');
        Route::get('client/projects/view/{id}', [ClientController::class, 'clientProjectView'])->name('client.project.view');
        Route::get('client/task/show/{id}/{notify?}', [ClientController::class, 'clientTaskshow'])->name('client.task.show');
        Route::post('client/message/', [SupportController::class, 'sendMessageClient'])->name('client.message.send');
        Route::get('client/brief', [ClientController::class, 'getClientBrief'])->name('client.brief');
    });
});
Route::group(['middleware' => 'auth'], function () {
    Route::post('verify/code',  [AdminController::class, 'verifyCode'])->name('verify.code');
}); 
// Admin Routes
Route::group(['middleware' => 'auth'], function () {
    Route::group(['prefix' => 'admin',  'middleware' => 'is_admin'], function(){
        Route::get('home', [AdminController::class, 'dashboard'])->name('admin.home');
        Route::get('edit-profile', [AdminController::class, 'editProfile'])->name('admin.edit.profile');
        Route::patch('update-profile/{id}', [AdminController::class, 'updateProfile'])->name('admin.update.profile');
        Route::get('change-password', [AdminController::class, 'changePassword'])->name('admin.change.password');
        Route::post('change-password', [AdminController::class, 'updatePassword'])->name('admin.update.password');
        Route::get('user/production/create', [AdminUserController::class, 'getProductionUser'])->name('admin.user.production.create');
        Route::get('user/production', [AdminUserController::class, 'getUserProduction'])->name('admin.user.production');
        Route::post('user/status', [AdminUserController::class, 'updateStatus'])->name('update.user.status');
        Route::post('user/sale/password', [AdminUserController::class, 'updateSalePassword'])->name('update.user.update.password');
        Route::get('user/sales', [AdminUserController::class, 'getUserSale'])->name('admin.user.sales');
        Route::post('user/sales', [AdminUserController::class, 'storeUserSale'])->name('admin.user.sales.store');
        Route::post('user/production', [AdminUserController::class, 'storeUserSale'])->name('admin.user.production.store');
        Route::post('user/sales/password', [AdminUserController::class, 'passwordUserSale'])->name('admin.user.password');
        Route::get('user/create', [AdminUserController::class, 'createUserSale'])->name('admin.user.sales.create');
        Route::get('user/sale/edit/{id}', [AdminUserController::class, 'editUserSale'])->name('admin.user.sales.edit');
        Route::get('user/production/edit/{id}', [AdminUserController::class, 'editUserProduction'])->name('admin.user.production.edit');
        Route::post('user/sale/update/{id}', [AdminUserController::class, 'updateUserSale'])->name('admin.user.sales.update');
        Route::resource('category', CategoryController::class);
        Route::resource('brand', BrandController::class);
        Route::resource('service', ServiceController::class);
        Route::resource('package', PackageController::class);
        Route::resource('currency', CurrencyController::class);
        Route::get('/service-list/{id}', [HomeController::class, 'serviceList'])->name('admin.service.list');
        Route::resource('client', AdminClientController::class, ['names' => 'admin.client']);
        Route::resource('merchant', MerchantController::class, ['names' => 'admin.merchant']);
        Route::post('client/create_auth/', [AdminClientController::class, 'createAuth'])->name('admin.client.createauth');
        Route::post('client/update_auth/', [AdminClientController::class, 'updateAuth'])->name('admin.client.updateauth');
        Route::get('client/agent/{brand_id?}', [AdminClientController::class, 'getAgent'])->name('admin.client.agent');
        Route::post('assign/support/', [AdminClientController::class, 'assignSupport'])->name('admin.assign.support');
        Route::post('client/agent/update', [AdminClientController::class, 'updateAgent'])->name('admin.client.update.agent');
        Route::resource('project', AdminProjectController::class, ['names' => 'admin.project']);
        Route::resource('task', AdminTaskController::class, ['names' => 'admin.task']);
        Route::post('admin/subtask/store', [AdminTaskController::class, 'adminSubtaskStore'])->name('admin.subtask.store');
        Route::get('client/{client}/{id}', [AdminClientController::class, 'showNotification'])->name('admin.client.shownotification');
        Route::get('create-invoice/{id}', [InvoiceController::class, 'index'])->name('admin.invoice.index');

app/Models/Project.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
    use HasFactory;

    protected $fillable = ['name', 'description', 'status', 'product_status', 'user_id', 'cost', 'client_id', 'brand_id', 'form_id', 'form_checker'];

    public function brand(){
        return $this->hasOne(Brand::class, 'id', 'brand_id');
    }
    
    public function client(){
        return $this->hasOne(User::class, 'id', 'client_id');
    }

    public function added_by(){
        return $this->hasOne(User::class, 'id', 'user_id');
    }

    public function project_category(){
        return $this->belongsToMany(Category::class, 'category_project');
    }

    public function tasks(){
        return $this->hasMany(Task::class);
    }
}

app/Http/Controllers/ProjectController.php
<?php

namespace App\Http\Controllers;

use App\Models\Project;
use App\Models\Client;
use App\Models\Category;
use App\Models\ProjectCategory;
use Illuminate\Http\Request;

class ProjectController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Project::whereIn('brand_id', Auth()->user()->brand_list())->get();
        return view('sale.project.index', compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $clients = Client::where('status', 1)->whereIn('brand_id', Auth()->user()->brand_list())->get();
        $category = Category::where('status', 1)->get();
        return view('sale.project.create', compact('clients', 'category'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'client' => 'required',
            'description' => 'required',
            'status' => 'required',
            'category' => 'required',
        ]);
        $get_client = Client::where('id', $request->input('client'))->first();
        $request->request->add(['brand_id' => $get_client->brand->id]);
        $request->request->add(['client_id' => $request->input('client')]);
        $request->request->add(['user_id' => auth()->user()->id]);
        $product = Project::create($request->all());
        $category = $request->input('category');
        for($i = 0; $i < count($category); $i++){
            $project_category = new ProjectCategory();
            $project_category->project_id = $product->id;
            $project_category->category_id = $category[$i];
            $project_category->save();
        }
        return redirect()->back()->with('success', 'Project created Successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function show(Project $project)
    {
        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $clients = Client::where('status', 1)->whereIn('brand_id', Auth()->user()->brand_list())->get();
        $data = Project::whereIn('brand_id', Auth()->user()->brand_list())->where('id', $id)->first();
        $category = Category::where('status', 1)->get();
        return view('sale.project.edit', compact('data', 'category', 'clients'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Project $project)
    {
        $request->validate([
            'name' => 'required',
            'client' => 'required',
            'description' => 'required',
            'status' => 'required',
            'category' => 'required',
        ]);
        $get_client = Client::where('id', $request->input('client'))->first();
        $request->request->add(['brand_id' => $get_client->brand->id]);
        $request->request->add(['client_id' => $request->input('client')]);
        $request->request->add(['user_id' => auth()->user()->id]);
        $project->update($request->all());
        $category = $request->input('category');
        $project->project_category()->sync($category);
        return redirect()->back()->with('success', 'Project Updated Successfully.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function destroy(Project $project)
    {
        //
    }
}

resources/views/manager/project/edit.blade.php
@extends('layouts.app-manager')

@section('content')
<div class="breadcrumb">
    <h1 class="mr-2">Edit Project (ID: {{$data->id}})</h1>
    <ul>
        <li>Projects</li>
        <li>Edit Project</li>
    </ul>
</div>
<div class="separator-breadcrumb border-top"></div>


<div class="row">
    <div class="col-md-12">
        <div class="card mb-4">
            <div class="card-body">
                <div class="card-title mb-3">Project Form</div>
                <form class="form" action="{{route('project.update', $data->id)}}" method="POST" enctype="multipart/form-data">
                    @csrf
                    @method('PATCH')
                    <div class="form-body">
                        <div class="row">
                            <div class="col-md-4 form-group mb-3">
                                <label for="name">Name <span>*</span></label>
                                <input type="text" id="name" class="form-control" value="{{old('name', $data->name)}}" placeholder="Name" name="name" required="required">
                            </div>
                            <div class="col-md-4 form-group mb-3">
                                <label for="client">Select Client <span>*</span></label>
                                <select name="client" id="client" class="form-control select2" >
                                    <option value="">Select Client</option>
                                    @foreach($clients as $client)
                                    @if($data->client_id == $client->id)
                                    <option value="{{$client->id}}" selected>{{$client->name}} {{$client->last_name}}</option>
                                    @else
                                    <option value="{{$client->id}}">{{$client->name}} {{$client->last_name}}</option>
                                    @endif
                                    @endforeach
                                </select>
                            </div>
                            <div class="col-md-4 form-group mb-3">
                                <label for="status">Select Status <span>*</span></label>
                                <select name="status" id="status" class="form-control" >
                                    <option value="1" {{$data->status == 1 ? 'selected' : ''}}>Active</option>
                                    <option value="0" {{$data->status == 0 ? 'selected' : ''}}>Deactive</option>
                                </select>
                            </div>
                            <div class="col-md-6 form-group mb-3">
                                <label for="description">Description <span>*</span></label>
                                <textarea class="form-control" name="description" id="description" cols="30" rows="5" required="required">{{old('description', $data->description)}}</textarea>
                            </div>
                            <div class="col-md-6 form-group mb-3">
                                <div class="inner-wrapper">
                                    <label for="category">Category <span>*</span></label>
                                    <select name="category[]" id="category" class="form-control select2" required multiple="multiple">
                                        @foreach($category as $categorys)
                                        <option value="{{ $categorys->id }}" {{ isset($data) && in_array($categorys->id, $data->project_category()->pluck('id')->toArray()) ? 'selected' : '' }}> {{$categorys->name}}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <button class="btn btn-primary" type="submit">Update Project</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@endsection

@push('scripts')
 
@endpush

resources/views/manager/project/index.blade.php
@extends('layouts.app-manager')
   
@section('content')
<div class="breadcrumb">
    <h1 class="mr-2">Projects</h1>
</div>
<div class="separator-breadcrumb border-top"></div>

<div class="row mb-4">
    <div class="col-md-12">
        <div class="card text-left">
            <div class="card-body">
                <form class="form">
                    <div class="form-body">
                        <div class="row">
                        <div class="col-md-3 col-lg form-group mb-0">
                                <select name="brand" class="form-control select2" >
                                    <option value="">Select Brand</option>
                                    @foreach($brands as $brand)
                                    <option value="{{$brand->id}}">{{$brand->name}}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="col-md-3 col-lg form-group mb-0">
                                <select name="client" class="form-control select2" >
                                    <option value="">Select Client</option>
                                    @foreach($clients as $client)
                                    <option value="{{$client->id}}">{{$client->name}} {{$client->last_name}}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="col-md-3 col-lg form-group mb-0">
                                <select name="user" class="form-control select2" >
                                    <option value="">Select Sale Agent</option>
                                    @foreach($users as $user)
                                    <option value="{{$user->id}}">{{$user->name}} {{$user->last_name}}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="col-md-3 col-lg form-group mb-0">
                                <select name="user" class="form-control select2" >
                                    <option value="">Select Category</option>
                                    @foreach($categorys as $category)
                                    <option value="{{$category->id}}">{{$category->name}}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="col-md-3 col-lg form-group mb-0">
                                <button class="btn btn-primary btn-block" type="submit">Search</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="card text-left">
            <div class="card-body">
                <h4 class="card-title mb-3">Project Details</h4>
                <div class="table-responsive">
                    <table class="display table table-striped table-bordered" id="zero_configuration_table" style="width:100%">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Name</th>
                                <th>Client</th>
                                <th>Assigned To</th>
                                <th>Brand</th>
                                <th>Reassign</th>
                                <th>Status</th>
                                <th>Active</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($data as $datas)
                            <tr>
                                <td>{{$datas->id}}</td>
                                <td>{{$datas->name}}</td>
                                <td>
                                    {{$datas->client->name}} {{$datas->client->last_name}}<br>
                                    {{$datas->client->email}}                                    
                                </td>
                                <td>
                                    {{$datas->added_by->name}} {{$datas->added_by->last_name}} <br>
                                    {{$datas->added_by->email}}
                                </td>
                                <td><button class="btn btn-info btn-sm">{{$datas->brand->name}}</button></td>
                                <td>
                                    <button class="btn btn-primary btn-sm" onclick="openReassign({{$datas->id}}, '{{$datas->brand->id}}')">Reassign</button>
                                </td>
                                <td>
                                    @if($datas->status == 1)
                                        <button class="btn btn-success btn-sm">Active</button>
                                    @else
                                        <button class="btn btn-danger btn-sm">Deactive</button>
                                    @endif
                                </td>
                                <td>
                                    @if($datas->form_checker == 1)
                                    <a href="{{ route('manager.form', ['form_id' => $datas->form_id, 'check' => $datas->form_checker, 'id' => $datas->id]) }}" class="btn btn-secondary btn-sm">Logo Form</a>
                                    @elseif($datas->form_checker == 2)
                                    <a href="{{ route('manager.form', ['form_id' => $datas->form_id, 'check' => $datas->form_checker, 'id' => $datas->id]) }}" class="btn btn-secondary btn-sm">Website Form</a>
                                    @elseif($datas->form_checker == 3)
                                    <a href="{{ route('manager.form', ['form_id' => $datas->form_id, 'check' => $datas->form_checker, 'id' => $datas->id]) }}" class="btn btn-secondary btn-sm">SMM Form</a>
                                    @elseif($datas->form_checker == 4)
                                    <a href="{{ route('manager.form', ['form_id' => $datas->form_id, 'check' => $datas->form_checker, 'id' => $datas->id]) }}" class="btn btn-secondary btn-sm">Content Form</a>
                                    @elseif($datas->form_checker == 5)
                                    <a href="{{ route('manager.form', ['form_id' => $datas->form_id, 'check' => $datas->form_checker, 'id' => $datas->id]) }}" class="btn btn-secondary btn-sm">SEO Form</a>
                                    @elseif($datas->form_checker == 6)
                                    <a href="{{ route('manager.form', ['form_id' => $datas->form_id, 'check' => $datas->form_checker, 'id' => $datas->id]) }}" class="btn btn-secondary btn-sm">Book Formatting & Publishing</a>
                                    @elseif($datas->form_checker == 7)
                                    <a href="{{ route('manager.form', ['form_id' => $datas->form_id, 'check' => $datas->form_checker, 'id' => $datas->id]) }}" class="btn btn-secondary btn-sm">Book Writing</a>
                                    @elseif($datas->form_checker == 8)
                                    <a href="{{ route('manager.form', ['form_id' => $datas->form_id, 'check' => $datas->form_checker, 'id' => $datas->id]) }}" class="btn btn-secondary btn-sm">Author Website</a>
                                    @elseif($datas->form_checker == 9)
                                    <a href="{{ route('manager.form', ['form_id' => $datas->form_id, 'check' => $datas->form_checker, 'id' => $datas->id]) }}" class="btn btn-secondary btn-sm">Editing & Proofreading</a>
                                    @elseif($datas->form_checker == 10)
                                    <a href="{{ route('manager.form', ['form_id' => $datas->form_id, 'check' => $datas->form_checker, 'id' => $datas->id]) }}" class="btn btn-secondary btn-sm">Book Cover Design</a>
                                    @endif
                                    <!-- <a href="{{ route('manager.project.edit', $datas->id) }}" class="btn btn-primary btn-icon btn-sm">
                                        <span class="ul-btn__icon"><i class="i-Edit"></i></span>
                                        <span class="ul-btn__text">Edit</span>
                                    </a> -->
                                </td>
                            </tr>
                            @endforeach
                            
                        </tbody>
                        <tfoot>
                            <tr>
                                <th>ID</th>
                                <th>Name</th>
                                <th>Client</th>
                                <th>Assigned To</th>
                                <th>Brand</th>
                                <th>Reassign</th>
                                <th>Status</th>
                                <th>Active</th>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="assignModel" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle-2" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalCenterTitle-2">Assign Agent</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
            </div>
            <form action="{{ route('manager.reassign.support') }}" method="post">
            @csrf
                <div class="modal-body">
                    <input type="hidden" name="id" id="assign_id">
                    <input type="hidden" name="form" id="form_id">
                    <div class="form-group">
                        <label class="col-form-label" for="agent-name-wrapper">Name:</label>
                        <select name="agent_id" id="agent-name-wrapper" class="form-control">

                        </select>
                    </div>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Close</button>
                    <button class="btn btn-primary ml-2" type="submit">Save changes</button>
                </div>
            </form>
        </div>
    </div>
</div>

@endsection

@push('scripts')
<script>
    function openReassign(id, brand_id){
        $('#agent-name-wrapper').html('');
        var url = "{{ route('manager.client.agent', ":id") }}";
        url = url.replace(':id', brand_id);
        $.ajax({
            type:'GET',
            url: url,
            success:function(data) {
                var getData = data.data;
                for (var i = 0; i < getData.length; i++) {
                    $('#agent-name-wrapper').append('<option value="'+getData[i].id+'">'+getData[i].name+ ' ' +getData[i].last_name+'</option>');
                }
            }
        });
        $('#assignModel').find('#assign_id').val(id);
        $('#assignModel').modal('show');
    }
</script>
@endpush